export const ADD_PHOTO = 'ADD_PHOTO';
export const RENAME_PHOTO = 'RENAME_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';

export const ADD_ALBUM = 'ADD_ALBUM';
export const RENAME_ALBUM = 'RENAME_ALBUM';
export const DELETE_ALBUM = 'DELETE_ALBUM';

export const PREVIEW_PHOTO_REQUEST = 'PREVIEW_PHOTO_REQUEST';
export const PREVIEW_PHOTO_FAILURE = 'PREVIEW_PHOTO_FAILURE';
export const PREVIEW_PHOTO_SUCCESS = 'PREVIEW_PHOTO_SUCCESS';

export const UPLOAD_PHOTO_REQUEST = 'UPLOAD_PHOTO_REQUEST';
export const UPLOAD_PHOTO_FAILURE = 'UPLOAD_PHOTO_FAILURE';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
